// 서울/인천/경기/강원 시군구 법정동코드(5자리) 목록.
// 행정구역 개편(예: 부천시 구 폐지, 강원도 → 강원특별자치도 전환)으로 변경될 수 있으니
// 실제 동기화 전에 행정표준코드관리시스템(https://www.code.go.kr)에서 최신값을 확인하세요.

export const REGION_CODES: { sido: string; sigungu: string; code: string }[] = [
  // 서울특별시
  { sido: "서울특별시", sigungu: "종로구", code: "11110" },
  { sido: "서울특별시", sigungu: "중구", code: "11140" },
  { sido: "서울특별시", sigungu: "용산구", code: "11170" },
  { sido: "서울특별시", sigungu: "성동구", code: "11200" },
  { sido: "서울특별시", sigungu: "광진구", code: "11215" },
  { sido: "서울특별시", sigungu: "동대문구", code: "11230" },
  { sido: "서울특별시", sigungu: "중랑구", code: "11260" },
  { sido: "서울특별시", sigungu: "성북구", code: "11290" },
  { sido: "서울특별시", sigungu: "강북구", code: "11305" },
  { sido: "서울특별시", sigungu: "도봉구", code: "11320" },
  { sido: "서울특별시", sigungu: "노원구", code: "11350" },
  { sido: "서울특별시", sigungu: "은평구", code: "11380" },
  { sido: "서울특별시", sigungu: "서대문구", code: "11410" },
  { sido: "서울특별시", sigungu: "마포구", code: "11440" },
  { sido: "서울특별시", sigungu: "양천구", code: "11470" },
  { sido: "서울특별시", sigungu: "강서구", code: "11500" },
  { sido: "서울특별시", sigungu: "구로구", code: "11530" },
  { sido: "서울특별시", sigungu: "금천구", code: "11545" },
  { sido: "서울특별시", sigungu: "영등포구", code: "11560" },
  { sido: "서울특별시", sigungu: "동작구", code: "11590" },
  { sido: "서울특별시", sigungu: "관악구", code: "11620" },
  { sido: "서울특별시", sigungu: "서초구", code: "11650" },
  { sido: "서울특별시", sigungu: "강남구", code: "11680" },
  { sido: "서울특별시", sigungu: "송파구", code: "11710" },
  { sido: "서울특별시", sigungu: "강동구", code: "11740" },

  // 인천광역시
  { sido: "인천광역시", sigungu: "중구", code: "28110" },
  { sido: "인천광역시", sigungu: "동구", code: "28140" },
  { sido: "인천광역시", sigungu: "미추홀구", code: "28177" },
  { sido: "인천광역시", sigungu: "연수구", code: "28185" },
  { sido: "인천광역시", sigungu: "남동구", code: "28200" },
  { sido: "인천광역시", sigungu: "부평구", code: "28237" },
  { sido: "인천광역시", sigungu: "계양구", code: "28245" },
  { sido: "인천광역시", sigungu: "서구", code: "28260" },
  { sido: "인천광역시", sigungu: "강화군", code: "28710" },
  { sido: "인천광역시", sigungu: "옹진군", code: "28720" },

  // 경기도
  { sido: "경기도", sigungu: "수원시 장안구", code: "41111" },
  { sido: "경기도", sigungu: "수원시 권선구", code: "41113" },
  { sido: "경기도", sigungu: "수원시 팔달구", code: "41115" },
  { sido: "경기도", sigungu: "수원시 영통구", code: "41117" },
  { sido: "경기도", sigungu: "성남시 수정구", code: "41131" },
  { sido: "경기도", sigungu: "성남시 중원구", code: "41133" },
  { sido: "경기도", sigungu: "성남시 분당구", code: "41135" },
  { sido: "경기도", sigungu: "의정부시", code: "41150" },
  { sido: "경기도", sigungu: "안양시 만안구", code: "41171" },
  { sido: "경기도", sigungu: "안양시 동안구", code: "41173" },
  { sido: "경기도", sigungu: "부천시", code: "41190" },
  { sido: "경기도", sigungu: "광명시", code: "41210" },
  { sido: "경기도", sigungu: "평택시", code: "41220" },
  { sido: "경기도", sigungu: "동두천시", code: "41250" },
  { sido: "경기도", sigungu: "안산시 상록구", code: "41271" },
  { sido: "경기도", sigungu: "안산시 단원구", code: "41273" },
  { sido: "경기도", sigungu: "고양시 덕양구", code: "41281" },
  { sido: "경기도", sigungu: "고양시 일산동구", code: "41285" },
  { sido: "경기도", sigungu: "고양시 일산서구", code: "41287" },
  { sido: "경기도", sigungu: "과천시", code: "41290" },
  { sido: "경기도", sigungu: "구리시", code: "41310" },
  { sido: "경기도", sigungu: "남양주시", code: "41360" },
  { sido: "경기도", sigungu: "오산시", code: "41370" },
  { sido: "경기도", sigungu: "시흥시", code: "41390" },
  { sido: "경기도", sigungu: "군포시", code: "41410" },
  { sido: "경기도", sigungu: "의왕시", code: "41430" },
  { sido: "경기도", sigungu: "하남시", code: "41450" },
  { sido: "경기도", sigungu: "용인시 처인구", code: "41461" },
  { sido: "경기도", sigungu: "용인시 기흥구", code: "41463" },
  { sido: "경기도", sigungu: "용인시 수지구", code: "41465" },
  { sido: "경기도", sigungu: "파주시", code: "41480" },
  { sido: "경기도", sigungu: "이천시", code: "41500" },
  { sido: "경기도", sigungu: "안성시", code: "41550" },
  { sido: "경기도", sigungu: "김포시", code: "41570" },
  { sido: "경기도", sigungu: "화성시", code: "41590" },
  { sido: "경기도", sigungu: "광주시", code: "41610" },
  { sido: "경기도", sigungu: "양주시", code: "41630" },
  { sido: "경기도", sigungu: "포천시", code: "41650" },
  { sido: "경기도", sigungu: "여주시", code: "41670" },
  { sido: "경기도", sigungu: "연천군", code: "41800" },
  { sido: "경기도", sigungu: "가평군", code: "41820" },
  { sido: "경기도", sigungu: "양평군", code: "41830" },

  // 강원특별자치도
  { sido: "강원특별자치도", sigungu: "춘천시", code: "51110" },
  { sido: "강원특별자치도", sigungu: "원주시", code: "51130" },
  { sido: "강원특별자치도", sigungu: "강릉시", code: "51150" },
  { sido: "강원특별자치도", sigungu: "동해시", code: "51170" },
  { sido: "강원특별자치도", sigungu: "태백시", code: "51190" },
  { sido: "강원특별자치도", sigungu: "속초시", code: "51210" },
  { sido: "강원특별자치도", sigungu: "삼척시", code: "51230" },
  { sido: "강원특별자치도", sigungu: "홍천군", code: "51720" },
  { sido: "강원특별자치도", sigungu: "횡성군", code: "51730" },
  { sido: "강원특별자치도", sigungu: "영월군", code: "51750" },
  { sido: "강원특별자치도", sigungu: "평창군", code: "51760" },
  { sido: "강원특별자치도", sigungu: "정선군", code: "51770" },
  { sido: "강원특별자치도", sigungu: "철원군", code: "51780" },
  { sido: "강원특별자치도", sigungu: "화천군", code: "51790" },
  { sido: "강원특별자치도", sigungu: "양구군", code: "51800" },
  { sido: "강원특별자치도", sigungu: "인제군", code: "51810" },
  { sido: "강원특별자치도", sigungu: "고성군", code: "51820" },
  { sido: "강원특별자치도", sigungu: "양양군", code: "51830" },
];
